name: MOve service
description: |
    A service to manage an individual game move
style: RESOURCE
uriTemplate: /games/{id}/moves/{move}
methods:
    GET:
        summary: Get one MOve
        notes: Get one MOve
        # implementation: api.getMOve
        request:
            parameters: []
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: &OkStatusCode 200
                reason: &OkReason Successful execution
                # validationSchema: getResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: getResource-responseBody.json
        testCases:
            -
                name: Get MOve
                description: Successfully retrieves one customer
                url: /games/{id}/moves/{move}
                template: testGetMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    # validationSchema: getResource-responseBody-validationSchema.json

    DELETE:
        summary: Delete a MOve
        notes: Delete a MOve
        # implementation: api.deleteMOve
        request:
            parameters: 
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the MOve to be deleted
                    default: 1
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: deleteResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: deleteResource-responseBody.json
        testCases:
            -
                name: Delete MOve
                description: Successfully delete the MOve
                url: /games/{id}/moves/{move}
                template: testDelMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"

    PUT:
        summary: Update a MOve
        notes: Update a MOve
        implementation: api.putMOve
        request:
            parameters:
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the MOve to be updated
                    default: 1
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: putResource-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: putResource-responseBody.json
        testCases:
            -
                name: Update MOve
                description: Succesfully updates a MOve
                url: /games/{id}/moves/{move}
                template: testPutMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: putResource-requestBody.json
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    body: putResource-responseBody.json
                    # validationSchema: putResource-responseBody-validationSchema.json
