## The server config file

# Use this environment by default, if server is started without the --env switch.
useEnvironment: development
#useEnvironment: production

environments:

  # This is the default configuration set
  default:
    documentRoot: .
    port: 3007
    restapiRoot: ..
    useRemoteServices: false
    remoteServices: []

  # Override the default config parameters with values specific to the development environment
  development:
    port: 3007
    documentRoot: ../webui

  # development environment with proxying the 'serviceUrlPrefix' requests to the local host
  devProxy:
    port: 3006
    documentRoot: ../webui
    proxyException:
      active: true
      urlPrefixList:
        - /monitoring/isAlive
        - /Flight/legs/.*/closeLeg
    remoteServices:
      -
        uri: /*
        active: true
        host: localhost
        port: 3008

  # production environment specific values
  production:
    port: 3008
    documentRoot: ../webui/build/demo-project/production
